In [1]:
from matchRunner import *
from player import *
from ultimateTicTacToe.ultimateBoardEvaluator import *
from hill_climbing import *
import random as rd

In [2]:
e = UltimateBoardEvaluatorFactory.firstEvaluator()

playerX = Player(e, True)
playerO = Player(e, False)
random_playerO = RandomPlayer(e, False)

#playAManualGame(playerX)
#%time playAGame(playerX, playerO, ((1, 1), (1, 2)), False, 1)
#%time playAGame(playerX, playerO, ((1, 1), (2, 2)), False, 2)

In [4]:
initial_weights = [-8.76258  ,  1.2146915, -0.9833173,  9.810604 , -5.5195103,
         2.0806534, -3.6834266,  2.1207073, -9.972995 ,  3.839281 ,
        -1.7329569,  4.648449 ,  6.241724 , -5.896732 , -5.9747896,
         1.0282923,  4.9491673, -0.6468066]
initial_score = 157.5

%time hill_climbing_all_weights(initial_weights, initial_score, 1, depth=2, workers=61)

Iteration: 0
Adjusted Weights:
[-8.76258    1.2146915 -0.9833173  9.810604  -5.5195103  2.0806534
 -3.6834266  2.1207073 -9.972995   3.839281  -1.7329569  4.648449
  6.241724  -5.896732  -5.9747896  1.0282923  4.9491673 -0.6468066]
Opponent: 0
Opponent: 1
Opponent: 2
Opponent: 3
Opponent: 4
[40, 130, 235]
Current Weights and Score:
[-8.76258    1.2146915 -0.9833173  9.810604  -5.5195103  2.0806534
 -3.6834266  2.1207073 -9.972995   3.839281  -1.7329569  4.648449
  6.241724  -5.896732  -5.9747896  1.0282923  4.9491673 -0.6468066]
157.5
CPU times: total: 2.09 s
Wall time: 26min 28s


(array([-8.76258  ,  1.2146915, -0.9833173,  9.810604 , -5.5195103,
         2.0806534, -3.6834266,  2.1207073, -9.972995 ,  3.839281 ,
        -1.7329569,  4.648449 ,  6.241724 , -5.896732 , -5.9747896,
         1.0282923,  4.9491673, -0.6468066], dtype=float32),
 157.5)

In [10]:
weights = [5, -5, 30, -30, 10, -10, 10, -10, 10, -10, 5, -5, 5, -5, 2, -2, 1, -1]

block_e = e.build_copy(weights)
block_o = Player(block_e, False)

%time playAllFirstMovesPool(playerX, block_o, depth = 2, workers = 61)

CPU times: total: 297 ms
Wall time: 5min 43s


(5, 68, 8)

In [5]:
goated_weights = [  5.1741295,    3.886535,     3.6193433,   13.318962,    16.745142,
  14.284059,    -7.861514,    22.770864,    16.7392,       0.45854726,
  -8.455032,   -13.811818,   -23.9487,      -2.6411142,   -7.2471147,
  -6.444899,   -12.166677,     6.4047003 ]

goated_e = e.build_copy(goated_weights)
goated_player = Player(goated_e, True)

random_weights = np.zeros(len(goated_weights))
for i in range(len(goated_weights)):
    random_weights[i] = rd.uniform(-20, 20)
print(random_weights)

random_weights_e = e.build_copy(random_weights)
random_weights_O = Player(random_weights_e, False)

%time playAllFirstMovesPool(goated_player, random_playerO, depth = 2, workers = 61)

[-17.49036437  -9.51656887  -5.95690373  12.76594024  -6.97691547
   6.90058764   4.51994633 -17.52830325  18.84040547  12.09316725
  -4.0116507   -8.8851653   -3.12036117   0.24997132   6.42489836
 -19.3861258    3.48687864   3.65654852]
CPU times: total: 188 ms
Wall time: 1min 45s


(77, 0, 4)

In [ ]:
%time hill_climbing_all_weights(e, 200, depth=2)

Iteration: 0
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
0.35802469135802467
Iteration: 1
[ 9.229254  -1.0666928  5.934885   5.9666834 10.860074   7.895881
 -2.00784    9.672351   8.28996   -1.3013495  3.3059795 -6.4734797
  1.786871   2.5228179  1.7456186  4.827737  -5.327338   3.803734 ]
0.7160493827160493
Iteration: 2
[  2.226826   -10.610563     8.585663    -0.999323     5.3675795
   5.558798   -11.217316    13.408637    12.769787    -8.733775
   0.75675815 -11.37673     -4.4549084   -6.7614427   -0.9514253
  -3.030544    -8.921607     8.777806  ]
0.7654320987654321
Iteration: 3
[  2.226826   -10.610563     8.585663    -0.999323     5.3675795
   5.558798   -11.217316    13.408637    12.769787    -8.733775
   0.75675815 -11.37673     -4.4549084   -6.7614427   -0.9514253
  -3.030544    -8.921607     8.777806  ]
0.7654320987654321
Iteration: 4
[  2.226826   -10.610563     8.585663    -0.999323     5.3675795
   5.558798   -11.217316    13.408637    12.769787    -8.733775
  

[  0.54916877  -4.0099425    5.013698    19.510653    10.64547
  10.369809    -3.5340283   21.644958    20.800991     2.2731774
  -5.5260153  -16.71961    -21.637262    -5.3573728   -2.666467
 -13.31815    -12.429291    13.634963  ]
0.9753086419753086
Iteration: 33
[  0.54916877  -4.0099425    5.013698    19.510653    10.64547
  10.369809    -3.5340283   21.644958    20.800991     2.2731774
  -5.5260153  -16.71961    -21.637262    -5.3573728   -2.666467
 -13.31815    -12.429291    13.634963  ]
0.9753086419753086
Iteration: 34
[  0.54916877  -4.0099425    5.013698    19.510653    10.64547
  10.369809    -3.5340283   21.644958    20.800991     2.2731774
  -5.5260153  -16.71961    -21.637262    -5.3573728   -2.666467
 -13.31815    -12.429291    13.634963  ]
0.9753086419753086
Iteration: 35
[  0.54916877  -4.0099425    5.013698    19.510653    10.64547
  10.369809    -3.5340283   21.644958    20.800991     2.2731774
  -5.5260153  -16.71961    -21.637262    -5.3573728   -2.666467
 -13.31815

In [ ]:
'''
0.9259259259259259
[  0.8092884   -2.9558444    0.9124725    8.544391     7.097348
  14.259165    -4.2338777   18.094831    17.270071    -7.870483
  -0.46121103 -17.759901   -13.998116   -11.809123    -5.884463
   0.45962194  -7.8783727    6.8139725 ]
'''

'''
0.9506172839506173
[  5.1741295    3.886535     3.6193433   13.318962    16.745142
  14.284059    -7.861514    22.770864    16.7392       0.45854726
  -8.455032   -13.811818   -23.9487      -2.6411142   -7.2471147
  -6.444899   -12.166677     6.4047003 ]
'''

'''
[  0.54916877  -4.0099425    5.013698    19.510653    10.64547
  10.369809    -3.5340283   21.644958    20.800991     2.2731774
  -5.5260153  -16.71961    -21.637262    -5.3573728   -2.666467
 -13.31815    -12.429291    13.634963  ]
'''

In [3]:
%time hill_climbing_per_weight(e, 1, depth=1)

Iteration: 0
D_weights:
[ 0.  1.  1.  1.  0.  1.  1.  0.  0.  1.  1. -1.  0. -1.  1.  1.  1.  1.]
Current Weights and Win Rate:
[ 1.         2.2136602  5.616823   9.871479   1.         1.5620427
  3.6201367  1.         1.         2.7347457  3.655716  -1.4852413
  1.        -8.45506    5.8541827  8.790466   6.142385   5.5279293]
0.5925925925925926
CPU times: total: 2.42 s
Wall time: 9min 19s


(array([ 1.       ,  2.2136602,  5.616823 ,  9.871479 ,  1.       ,
         1.5620427,  3.6201367,  1.       ,  1.       ,  2.7347457,
         3.655716 , -1.4852413,  1.       , -8.45506  ,  5.8541827,
         8.790466 ,  6.142385 ,  5.5279293], dtype=float32),
 0.5925925925925926)

In [3]:
%time hill_climbing_all_weights(e, 50, depth=2)

Iteration: 0
[ 7.2538576  -0.34805182  4.31394     5.8828425   0.8499103   7.692521
  1.7417085  -3.9635115  -0.50726515  5.73548     8.3643675   4.4870267
 -6.4648113  -2.6487124   8.883279   -1.1882409   8.085255   -5.1961374 ]
0.43209876543209874
Iteration: 1
[ 7.2538576  -0.34805182  4.31394     5.8828425   0.8499103   7.692521
  1.7417085  -3.9635115  -0.50726515  5.73548     8.3643675   4.4870267
 -6.4648113  -2.6487124   8.883279   -1.1882409   8.085255   -5.1961374 ]
0.43209876543209874
Iteration: 2
[ 7.2538576  -0.34805182  4.31394     5.8828425   0.8499103   7.692521
  1.7417085  -3.9635115  -0.50726515  5.73548     8.3643675   4.4870267
 -6.4648113  -2.6487124   8.883279   -1.1882409   8.085255   -5.1961374 ]
0.43209876543209874
Iteration: 3
[  3.4623291   -8.16317     -2.2701256   14.184399     8.086923
   4.0235705    3.8743196   -8.106066    -0.5230459   -3.5149632
  16.11431     -3.9775388  -14.108885   -10.16844      0.8123136
   4.9791665    5.5949845    0.86150813]
0.

[ 18.631538   -2.7034864  15.979937   12.227591    9.496304   16.309149
   4.13843    -4.4744945   4.642535  -10.10908     2.8184934 -14.267908
 -14.935613  -18.40167    15.221554   12.44066     1.3837558   4.140982 ]
0.7283950617283951
Iteration: 33
[ 18.631538   -2.7034864  15.979937   12.227591    9.496304   16.309149
   4.13843    -4.4744945   4.642535  -10.10908     2.8184934 -14.267908
 -14.935613  -18.40167    15.221554   12.44066     1.3837558   4.140982 ]
0.7283950617283951
Iteration: 34
[ 18.631538   -2.7034864  15.979937   12.227591    9.496304   16.309149
   4.13843    -4.4744945   4.642535  -10.10908     2.8184934 -14.267908
 -14.935613  -18.40167    15.221554   12.44066     1.3837558   4.140982 ]
0.7283950617283951
Iteration: 35
[ 18.631538   -2.7034864  15.979937   12.227591    9.496304   16.309149
   4.13843    -4.4744945   4.642535  -10.10908     2.8184934 -14.267908
 -14.935613  -18.40167    15.221554   12.44066     1.3837558   4.140982 ]
0.7283950617283951
Iteration:

(array([ 14.224978 ,   1.9072839,  12.347659 ,   8.790984 ,   5.139256 ,
         15.328289 ,  11.477053 ,  -7.0327916,   6.7936745,  -4.745274 ,
         -3.230234 ,  -8.870525 , -14.854856 , -27.009357 ,  23.251766 ,
          8.257502 ,  -5.3605733,   7.007347 ], dtype=float32),
 0.8024691358024691)

In [4]:
# play all first moves with async
%time playAllFirstMovesPool(playerX, playerO, depth = 2, workers = 60)

CPU times: total: 109 ms
Wall time: 1min 32s


(29, 33)

In [ ]:
# initial win rates are (9, 70) for depth 1, (29, 33) for depth 2

In [ ]:
# Depth 2, 10 iterations
# [ -6   9   2   9  11 -19  -9   8  21   8  -4 -11   0   7  -3  12 -17   3]
# Win rate = 0.7901234567901234

In [3]:
new_weights = [-6,9,2,9,11,-19,-9,8,21,8,-4,-11,0,7,-3,12,-17,3]
new_e = e.build_copy(new_weights)

new_playerX = Player(new_e, True)
new_playerO = Player(new_e, False)
random_playerO = RandomPlayer(new_e, False)

In [11]:
# depth 2 50 iterations, win rate = 0.8024691358024691
weights_50_iteration = [ 14.224978 ,   1.9072839,  12.347659 ,   8.790984 ,   5.139256 ,
         15.328289 ,  11.477053 ,  -7.0327916,   6.7936745,  -4.745274 ,
         -3.230234 ,  -8.870525 , -14.854856 , -27.009357 ,  23.251766 ,
          8.257502 ,  -5.3605733,   7.007347 ]

CPU times: total: 78.1 ms
Wall time: 9min 39s


(61, 6)